apiVersion: v1
kind: ConfigMap
metadata:
  name: medplum-server-config
  namespace: provider-registry
data:
  medplum.config.json: |
    {
      "port": 8103,
      "baseUrl": "http://localhost:8103",
      "issuer": "http://localhost:8103",
      "jwksUrl": "http://localhost:8103/.well-known/jwks.json",
      "authorizeUrl": "http://localhost:8103/oauth2/authorize",
      "tokenUrl": "http://localhost:8103/oauth2/token",
      "userInfoUrl": "http://localhost:8103/oauth2/userinfo",
      "appUrl": "http://localhost:3001",
      "binaryStorage": "file:./binary/",
      "storageBaseUrl": "http://localhost:8103/storage/",
      "signingKeyPassphrase": "medplum",
      "supportEmail": "support@example.com",
      "database": {
        "host": "postgres-service",
        "port": 5432,
        "dbname": "medplum",
        "username": "medplum",
        "password": "${DATABASE_PASSWORD}"
      },
      "redis": {
        "host": "redis-service",
        "port": 6379
      },
      "bullmq": {
        "removeOnComplete": {
          "count": 100
        },
        "removeOnFail": {
          "count": 100
        }
      },
      "logLevel": "info",
      "logRequests": false
    }
